### ISSUE TITLE
The whole currency bag of cats

### ISSUE THREAD

**Issue by hptt** [sunny/killbills#1]
Hi, I haven't looked into the source yet, but it looks like i cannot have per-user currencies nor per-bill ones. The latter might lead to over-engineering, but the former is really essential if you don't expect everyone to have a self-hosted instance where customization of the site-wide currency would be possible.

**Comment by sunny** [comment]
You are absolutely right @hptt that is an absolute prerequisite. It doesn't have to be a gigantic bag of cats though, it could just be using `current_user.currency_symbol` whenever we want to show a `$`.

**Comment by sunny** [comment]
You're welcome to implement it, too! ;)

**Comment by sunny** [comment]
Thanks for reporting the issue by the way, @hptt !
